'use client';

import Link from 'next/link';
import { ArrowUpRight, ChevronRight, CircleDot, ShieldCheck } from 'lucide-react';

const nodes = [
  { label: 'CUSTOMER', x: '18%', y: '24%', tone: 'bg-success' },
  { label: 'TRANSACTION', x: '51%', y: '42%', tone: 'bg-accent-blue' },
  { label: 'DEVICE', x: '78%', y: '24%', tone: 'bg-warning' },
  { label: 'IP ADDRESS', x: '18%', y: '72%', tone: 'bg-danger' },
  { label: 'PAYMENT METHOD', x: '78%', y: '73%', tone: 'bg-accent-blue' },
];

export default function Home() {
  return <main className="min-h-screen bg-app text-primary">
    <header className="max-w-7xl mx-auto px-6 lg:px-12 py-7 flex items-center justify-between border-b border-subtle">
      <Link href="/" className="flex items-center gap-3 no-underline"><ShieldCheck className="w-5 h-5 text-accent-blue" /><span className="font-bold tracking-[0.2em] text-sm">RISKGRAPH</span></Link>
      <nav className="hidden md:flex items-center gap-8 text-xs text-muted"><a href="#method" className="hover:text-primary">How it works</a><a href="#why" className="hover:text-primary">Why it matters</a><Link href="/dashboard" className="text-primary flex items-center gap-1">Open console <ArrowUpRight className="w-3.5 h-3.5" /></Link></nav>
    </header>

    <section className="max-w-7xl mx-auto px-6 lg:px-12 py-20 lg:py-28 grid lg:grid-cols-2 gap-16 items-center">
      <div className="animate-draw-in"><p className="text-xs font-mono tracking-[0.18em] text-accent-blue mb-7">REAL-TIME PAYMENT RISK INTELLIGENCE</p><h1 className="font-display text-5xl md:text-7xl leading-[.98] tracking-tight text-balance max-w-xl">Fraud rarely looks suspicious <em className="text-muted">one payment at a time.</em></h1><p className="mt-8 text-base md:text-lg leading-7 text-muted max-w-lg">RISKGRAPH connects transactions, devices, accounts, payment methods and infrastructure to reveal coordinated payment attacks before they scale.</p><div className="flex flex-wrap items-center gap-5 mt-10"><Link href="/dashboard" className="bg-accent-blue text-surface-primary px-5 py-3 text-xs font-bold tracking-wide no-underline hover:opacity-90">Explore the risk console <ArrowUpRight className="inline ml-2 w-3.5 h-3.5" /></Link><a href="#story" className="text-xs font-semibold text-primary no-underline border-b border-primary pb-1">See how RISKGRAPH works</a></div></div>
      <div className="relative min-h-[390px] bg-surface border border-subtle overflow-hidden animate-draw-in" style={{ animationDelay: '.15s' }}><div className="absolute inset-0 bg-grid-pattern opacity-40" /><div className="absolute inset-8 border border-subtle/60" /><div className="absolute left-[18%] right-[18%] top-[33%] border-t border-accent-blue/40 rotate-[25deg]" /><div className="absolute left-[18%] right-[18%] top-[63%] border-t border-danger/30 rotate-[-24deg]" /><div className="absolute left-[26%] right-[25%] top-[49%] border-t border-accent-blue/50" />{nodes.map((node, i) => <div key={node.label} className="absolute flex flex-col items-center gap-2" style={{ left: node.x, top: node.y, animation: `draw-in .7s ease ${.3 + i * .12}s both` }}><div className={`size-3 rounded-full ${node.tone} ring-8 ring-surface`} /><span className="text-[9px] font-mono tracking-wider text-muted whitespace-nowrap">{node.label}</span></div>)}<div className="absolute bottom-5 left-6 right-6 flex justify-between border-t border-subtle pt-3 text-[9px] font-mono text-muted"><span>RELATIONSHIP GRAPH / LIVE</span><span>5 entities connected</span></div></div>
    </section>

    <section id="story" className="max-w-7xl mx-auto px-6 lg:px-12 pb-24"><div className="grid md:grid-cols-3 border-y border-subtle"><article className="p-8 md:p-12 border-b md:border-b-0 md:border-r border-subtle"><p className="text-xs font-mono text-muted mb-14">INDIVIDUAL TRANSACTIONS</p><div className="flex flex-col gap-5 font-mono"><span className="flex justify-between text-sm"><b className="font-normal">₹2,499</b><small className="text-success">LOW RISK</small></span><span className="flex justify-between text-sm"><b className="font-normal">₹799</b><small className="text-success">LOW RISK</small></span><span className="flex justify-between text-sm"><b className="font-normal">₹1,299</b><small className="text-success">LOW RISK</small></span></div><h2 className="font-display text-3xl mt-12">Individually, they look ordinary.</h2></article><article className="p-8 md:p-12 border-b md:border-b-0 md:border-r border-subtle"><p className="text-xs font-mono text-muted mb-14">THE CONNECTION</p><div className="flex flex-col gap-4 text-sm"><span className="flex items-center gap-3"><CircleDot className="w-4 h-4 text-accent-blue" />same device</span><span className="flex items-center gap-3"><CircleDot className="w-4 h-4 text-warning" />same IP address</span><span className="flex items-center gap-3"><CircleDot className="w-4 h-4 text-danger" />same infrastructure</span></div><h2 className="font-display text-3xl mt-12">But payments don&apos;t exist in isolation.</h2></article><article className="p-8 md:p-12"><p className="text-xs font-mono text-muted mb-14">THE ATTACK</p><div className="font-mono text-sm flex flex-col gap-3"><span>14 accounts</span><span>2 devices</span><span>1 IP address</span><span>38 transactions</span></div><h2 className="font-display text-3xl mt-12">The pattern appears between the payments.</h2></article></div></section>

    <section id="method" className="bg-surface border-y border-subtle"><div className="max-w-7xl mx-auto px-6 lg:px-12 py-24"><div className="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-16"><div><p className="text-xs font-mono text-accent-blue tracking-widest mb-5">HOW IT WORKS</p><h2 className="font-display text-5xl text-balance">From signal to<br /><em className="text-muted">containment.</em></h2></div><p className="text-sm text-muted max-w-xs leading-6">A clearer view of coordinated activity, designed for decisions that hold up under pressure.</p></div><div className="grid md:grid-cols-4 border-t border-subtle">{['Score the payment','Map the relationships','Detect coordinated activity','Contain the attack'].map((step, i) => <div key={step} className="py-7 pr-7 border-b md:border-b-0 md:border-r border-subtle md:last:border-r-0 md:pl-7 first:pl-0"><span className="font-mono text-xs text-muted">0{i + 1}</span><h3 className="font-display text-2xl mt-8">{step}</h3><ChevronRight className="w-4 h-4 text-accent-blue mt-8" /></div>)}</div></div></section>

    <section id="why" className="max-w-7xl mx-auto px-6 lg:px-12 py-24 flex flex-col md:flex-row justify-between gap-10"><div><p className="text-xs font-mono text-muted tracking-widest mb-5">WHY IT MATTERS</p><h2 className="font-display text-4xl md:text-5xl max-w-xl">Stop investigating payments one by one.</h2></div><div className="max-w-sm"><p className="text-sm leading-6 text-muted">Transaction-only detection asks whether a payment is suspicious. Network-aware detection asks what is moving through it — and where to intervene.</p><Link href="/dashboard" className="inline-flex items-center gap-2 mt-8 text-sm font-semibold text-primary border-b border-primary pb-2 no-underline">Open RISKGRAPH <ArrowUpRight className="w-4 h-4" /></Link></div></section>
    <footer className="max-w-7xl mx-auto px-6 lg:px-12 py-7 border-t border-subtle flex justify-between text-[10px] font-mono text-muted"><span>RISKGRAPH / PAYMENT RISK INTELLIGENCE</span><span>BUILT FOR THE MOMENT BETWEEN SIGNAL AND ACTION</span></footer>
  </main>;
}
